# Generated by Django 4.2.1 on 2023-12-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regcapacitacion',
            old_name='idregistro',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='regexamen',
            old_name='idregistro',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='regmedico',
            old_name='idregistro',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='regterreno',
            old_name='idterreno',
            new_name='id',
        ),
    ]
